# Generated by Django 4.2.5 on 2023-09-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='transaction.category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='meter',
            field=models.ManyToManyField(blank=True, null=True, to='transaction.meter'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='meter_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
