# Generated by Django 4.2.5 on 2023-09-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='meter',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ManyToManyField(blank=True, to='transaction.category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='meter',
            field=models.ManyToManyField(blank=True, to='transaction.meter'),
        ),
    ]
