# Generated by Django 4.2.5 on 2023-09-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_category_name_alter_meter_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenditureTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('meter_quantity', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('price_per_meter_unit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('category', models.ManyToManyField(blank=True, to='transaction.category')),
                ('meter', models.ManyToManyField(blank=True, to='transaction.meter')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfitableTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('income_type', models.ManyToManyField(blank=True, to='transaction.incometype')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='TransactionType',
        ),
    ]
